### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by morganzis** [phit/discord-maroon-theme#15]
Hi! This is one of my favorite themes. However, it has not worked for me in a while. I've reinstalled the theme, betterdiscord, etc. I have dark mode on and everything, but it doesn't show up anymore. 

![Screenshot_60](https://user-images.githubusercontent.com/101417446/157905831-66c06be8-e551-4917-b7ea-1a1e2d22bb11.jpg)

**Comment by phit** [comment]
Hey, thanks for letting me know, I assume you are using [this file](https://github.com/phit/discord-maroon-theme/blob/master/maroon.theme.css), I just fixed the link it's pointing to. So if you redownload that it should work again.

**Comment by morganzis** [comment]
Thank you so much, it worked! :)

**Comment by phit** [comment]
Sweet, I'll be fixing a bunch of stuff that's currently broken later today, like wrong color in search and most of the event stuff isn't properly recolored right now.
Thank you for using my theme!
