### ISSUE TITLE
Hovering over messages doesn't highlight them. 

### ISSUE THREAD

**Issue by makimwah** [phit/discord-maroon-theme#16]
The title is pretty self-explanatory. Hovering over messages doesn't highlight them as it should. [Here's an example of what it's supposed to look like.](https://files.catbox.moe/927c8j.gif) [And here is footage of the theme.](https://files.catbox.moe/i6zmfp.gif)

**Comment by phit** [comment]
Thanks for letting me know, just posted an update here and on userstyles with a fix. Let me know if you have any more suggestions!
