### ISSUE TITLE
half is black half is maroon?

### ISSUE THREAD

**Issue by flynnflynnflynn** [phit/discord-maroon-theme#2]
![marronblackissue](https://user-images.githubusercontent.com/42096208/43678371-371b2a12-97e0-11e8-9b62-d3897d600a5e.PNG)
???? how do i fix this

**Comment by phit** [comment]
yeah discord likes breaking stuff and I'm on vacation, I'll push a temporary fix in a few minutes

**Comment by flynnflynnflynn** [comment]
rad ty
